name: Docker Build

on:
  push:
    tags:
    branches:
      - main
      - development

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Wait for checks to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Docker build'
          running-workflow-name: 'Verify'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Build Image
        run: docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Tag & Push branch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Tag & Push latest image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
